# alerts/alert_rules.yml
groups:
  - name: system_alerts
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: node:cpu_utilization:rate5m > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }} for more than 5 minutes."

      - alert: CriticalCPUUsage
        expr: node:cpu_utilization:rate5m > 95
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Critical CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }} for more than 2 minutes."

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: node:memory_utilization:ratio > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }} for more than 5 minutes."

      - alert: CriticalMemoryUsage
        expr: node:memory_utilization:ratio > 95
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Critical memory usage detected on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }} for more than 2 minutes."

      # Low Memory Available
      - alert: LowMemoryAvailable
        expr: node:memory_available:bytes < 100*1024*1024  # Less than 100MB
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Very low memory available on {{ $labels.instance }}"
          description: "Only {{ $value | humanize1024 }}B memory available on {{ $labels.instance }}."

      # High Disk Usage
      - alert: HighDiskUsage
        expr: node:disk_utilization:ratio > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High disk usage detected on {{ $labels.instance }}"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} ({{ $labels.mountpoint }}) for more than 5 minutes."

      - alert: CriticalDiskUsage
        expr: node:disk_utilization:ratio > 95
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Critical disk usage detected on {{ $labels.instance }}"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} ({{ $labels.mountpoint }}) for more than 2 minutes."

      # High Load Average
      - alert: HighLoadAverage
        expr: node:load_average:ratio > 2
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High load average on {{ $labels.instance }}"
          description: "Load average is {{ $value }} on {{ $labels.instance }} for more than 5 minutes."

      # Node Down
      - alert: NodeDown
        expr: up{job="node-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Node Exporter is down"
          description: "Node Exporter on {{ $labels.instance }} has been down for more than 1 minute."

  - name: application_alerts
    rules:
      # High HTTP Error Rate
      - alert: HighHTTPErrorRate
        expr: http:error_rate:5m > 5
        for: 5m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High HTTP error rate detected"
          description: "HTTP error rate is {{ $value }}% for more than 5 minutes."

      - alert: CriticalHTTPErrorRate
        expr: http:error_rate:5m > 15
        for: 2m
        labels:
          severity: critical
          service: application
        annotations:
          summary: "Critical HTTP error rate detected"
          description: "HTTP error rate is {{ $value }}% for more than 2 minutes."

      # High Response Time
      - alert: HighResponseTime
        expr: http:response_time:p95 > 1
        for: 5m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for more than 5 minutes."

      - alert: VeryHighResponseTime
        expr: http:response_time:p95 > 5
        for: 2m
        labels:
          severity: critical
          service: application
        annotations:
          summary: "Very high response time detected"
          description: "95th percentile response time is {{ $value }}s for more than 2 minutes."

      # Prometheus Down
      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 1m
        labels:
          severity: critical
          service: monitoring
        annotations:
          summary: "Prometheus is down"
          description: "Prometheus has been down for more than 1 minute."

  - name: blackbox_alerts
    rules:
      # Website Down
      - alert: WebsiteDown
        expr: probe_success == 0
        for: 2m
        labels:
          severity: critical
          service: website
        annotations:
          summary: "Website is down: {{ $labels.instance }}"
          description: "{{ $labels.instance }} has been down for more than 2 minutes."

      # High Response Time
      - alert: HighWebsiteResponseTime
        expr: blackbox:probe_duration:avg5m > 5
        for: 5m
        labels:
          severity: warning
          service: website
        annotations:
          summary: "High response time for {{ $labels.instance }}"
          description: "Response time for {{ $labels.instance }} is {{ $value }}s for more than 5 minutes."

      # SSL Certificate Expiring
      - alert: SSLCertificateExpiring
        expr: blackbox:ssl_cert_expiry:days < 30
        for: 1m
        labels:
          severity: warning
          service: ssl
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value }} days."

      - alert: SSLCertificateExpiringSoon
        expr: blackbox:ssl_cert_expiry:days < 7
        for: 1m
        labels:
          severity: critical
          service: ssl
        annotations:
          summary: "SSL certificate expiring very soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value }} days."

      # HTTP Status Code Alerts
      - alert: HTTPStatusError
        expr: probe_http_status_code >= 400
        for: 2m
        labels:
          severity: warning
          service: website
        annotations:
          summary: "HTTP error status code"
          description: "{{ $labels.instance }} returned status code {{ $value }} for more than 2 minutes."

  - name: infrastructure_alerts
    rules:
      # Too Many Restarts
      - alert: ContainerRestarting
        expr: rate(prometheus_notifications_total{job="prometheus"}[5m]) > 0
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "Container restarting frequently"
          description: "Container has restarted {{ $value }} times in the last 5 minutes."

      # Disk Will Fill Up
      - alert: DiskWillFillUp
        expr: |
          (
            predict_linear(node:disk_free:bytes[1h], 4*3600) < 0
          ) and (
            node:disk_utilization:ratio > 70
          )
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Disk will fill up in 4 hours"
          description: "Disk on {{ $labels.instance }} ({{ $labels.mountpoint }}) will fill up in approximately 4 hours based on current usage trends."

      # Network Issues
      - alert: HighNetworkErrors
        expr: |
          rate(node_network_receive_errs_total[5m]) > 10 or
          rate(node_network_transmit_errs_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: network
        annotations:
          summary: "High network error rate"
          description: "Network errors detected on {{ $labels.instance }} interface {{ $labels.device }}: {{ $value }} errors/sec."