# rules/recording_rules.yml
groups:
  - name: node_recording_rules
    interval: 30s
    rules:
      # CPU Usage
      - record: node:cpu_utilization:rate5m
        expr: |
          (
            1 - rate(node_cpu_seconds_total{mode="idle"}[5m])
          ) * 100

      - record: node:cpu_utilization:rate1m
        expr: |
          (
            1 - rate(node_cpu_seconds_total{mode="idle"}[1m])
          ) * 100

      # Memory Usage
      - record: node:memory_utilization:ratio
        expr: |
          (
            1 - (
              node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes
            )
          ) * 100

      - record: node:memory_available:bytes
        expr: node_memory_MemAvailable_bytes

      # Disk Usage
      - record: node:disk_utilization:ratio
        expr: |
          (
            1 - (
              node_filesystem_avail_bytes{fstype!="tmpfs",fstype!="devtmpfs"} / 
              node_filesystem_size_bytes{fstype!="tmpfs",fstype!="devtmpfs"}
            )
          ) * 100

      - record: node:disk_free:bytes
        expr: |
          node_filesystem_avail_bytes{fstype!="tmpfs",fstype!="devtmpfs"}

      # Network I/O
      - record: node:network_receive:rate5m
        expr: |
          rate(node_network_receive_bytes_total{device!="lo"}[5m])

      - record: node:network_transmit:rate5m
        expr: |
          rate(node_network_transmit_bytes_total{device!="lo"}[5m])

      # Load Average
      - record: node:load_average:ratio
        expr: |
          node_load1 / count(count(node_cpu_seconds_total{mode="idle"}) by (cpu))

  - name: application_recording_rules
    interval: 30s
    rules:
      # HTTP Request Rate
      - record: http:request_rate:5m
        expr: |
          rate(prometheus_http_requests_total[5m])

      # HTTP Error Rate
      - record: http:error_rate:5m
        expr: |
          rate(prometheus_http_requests_total{code=~"4..|5.."}[5m]) / 
          rate(prometheus_http_requests_total[5m]) * 100

      # Blackbox Success Rate
      - record: blackbox:success_rate:5m
        expr: |
          avg_over_time(probe_success[5m]) * 100

      # Response Time Percentiles
      - record: http:response_time:p95
        expr: |
          histogram_quantile(0.95, 
            rate(prometheus_http_request_duration_seconds_bucket[5m])
          )

      - record: http:response_time:p99
        expr: |
          histogram_quantile(0.99, 
            rate(prometheus_http_request_duration_seconds_bucket[5m])
          )

  - name: blackbox_recording_rules
    interval: 30s
    rules:
      # Probe duration
      - record: blackbox:probe_duration:avg5m
        expr: |
          avg_over_time(probe_duration_seconds[5m])

      # SSL certificate expiry days
      - record: blackbox:ssl_cert_expiry:days
        expr: |
          (probe_ssl_earliest_cert_expiry - time()) / 86400

      # HTTP response time
      - record: blackbox:http_duration:avg5m
        expr: |
          avg_over_time(probe_http_duration_seconds[5m])